name: LINE Notify example
on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # - uses: snow-actions/line-notify@v1.0.0
      - uses: jun-shimoji/gha-sample@0.0.3
        with:
          my_url: ${{ secrets.MY_URL }}
          # access_token: ${{ secrets.MY_URL }}
          # message: "hello world"